// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Article = { id: string, url: string, title: string, title_zh: string, source: string, category: string, published_at: string | null, content_text: string, fetched_at: string, 
/**
 * rss = auto-ingested; url / file = user-imported (never purged by refresh).
 */
origin: string, };
