// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Home-list row: excerpt only. Full body stays on `Article` / get_article.
 */
export type ArticleListItem = { id: string, url: string, title: string, title_zh: string, source: string, category: string, published_at: string | null, excerpt: string, fetched_at: string, origin: string, summary_zh: string, last_opened_at: string | null, open_count: number, };
