// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Article = { id: string, url: string, title: string, title_zh: string, source: string, category: string, published_at: string | null, content_text: string, fetched_at: string, 
/**
 * rss = auto-ingested; url / file = user-imported (never purged by refresh).
 */
origin: string, 
/**
 * LLM-generated Simplified Chinese blurb, at most 50 characters.
 */
summary_zh: string, 
/**
 * Set when the reader is opened. Implicit; never asked.
 */
last_opened_at: string | null, open_count: number, };
