// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeedSource = { id: string, name: string, category: string, url: string, enabled: boolean, 
/**
 * curated = built-in seed; user = subscribed via manage UI
 */
origin: string, description: string, };
