// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved phrase / collocation with its own spaced-repetition state,
 * kept separate from the single-word `vocab` library.
 */
export type PhraseItem = { id: string, phrase: string, meaning_zh: string, 
/**
 * idiom / phrasal verb / collocation / 固定搭配 …
 */
usage: string, context_sentence: string, article_id: string | null, status: string, interval_days: number, reps: number, consecutive_know: number, next_review_at: string, created_at: string, };
