// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一行摘录。出处是写入时的快照，因此源文章被 purge 之后仍可阅读。
 */
export type SavedSentence = { id: string, article_id: string | null, quote: string, 
/**
 * 段落在 `content_text` 段落序列里的序号；-1 = 未知。
 */
para_index: bigint, source_title: string, source_url: string, created_at: string, };
