// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VocabItem = { id: string, term: string, definition_zh: string, word_type: string, collocations: Array<string>, context_sentence: string, article_id: string | null, status: string, interval_days: number, reps: number, consecutive_know: number, next_review_at: string, created_at: string, };
