import { defaultReadingPrefs } from "../readingPrefs";
import type { AppConfig as RustAppConfig } from "../../src-tauri/bindings/AppConfig";

export type { Article } from "../../src-tauri/bindings/Article";
export type { ArticleListItem } from "../../src-tauri/bindings/ArticleListItem";
export type { ArticleView } from "../../src-tauri/bindings/ArticleView";
export type { FeedCategory } from "../../src-tauri/bindings/FeedCategory";
export type { FeedDiscoverCandidate } from "../../src-tauri/bindings/FeedDiscoverCandidate";
export type { FeedSource } from "../../src-tauri/bindings/FeedSource";
export type { FeedValidation } from "../../src-tauri/bindings/FeedValidation";
export type { FullTranslateResult } from "../../src-tauri/bindings/FullTranslateResult";
export type { RefreshProgress } from "../../src-tauri/bindings/RefreshProgress";
export type { RefreshResult } from "../../src-tauri/bindings/RefreshResult";
export type { TranslateProgress } from "../../src-tauri/bindings/TranslateProgress";
export type { TranslationRow } from "../../src-tauri/bindings/TranslationRow";
export type { VocabItem } from "../../src-tauri/bindings/VocabItem";
export type { LearningStats } from "../../src-tauri/bindings/LearningStats";
/** Generated by ts-rs from the Rust `config::AppConfig` — single source of truth. */
export type { AppConfig } from "../../src-tauri/bindings/AppConfig";

export function defaultAppConfig(): RustAppConfig {
  return {
    base_url: "https://api.openai.com/v1",
    api_key: "",
    model: "gpt-4o-mini",
    disabled_feeds: [],
    cefr_level: "B1",
    freq_band: 3000,
    vocab_placement_done: false,
    vocab_placement_l: null,
    vocab_placement_at: null,
    vocab_placement_skipped: false,
    article_retention_days: 14,
    ...defaultReadingPrefs(),
  };
}
