use super::FeedSource;

fn feed(id: &str, name: &str, category: &str, url: &str) -> FeedSource {
    FeedSource {
        id: id.into(),
        name: name.into(),
        category: category.into(),
        url: url.into(),
        enabled: true,
        origin: "curated".into(),
        description: String::new(),
    }
}

/// Classic news + well-known blogs/newsletters + AI-oriented tech.
/// Prefer free/full-text article feeds; no podcasts (show notes only).
pub fn curated_feeds() -> Vec<FeedSource> {
    vec![
        // tech — AI / general tech news & commentary
        feed(
            "mit-technology-review",
            "MIT Technology Review",
            "tech",
            "https://www.technologyreview.com/feed/",
        ),
        feed(
            "mit-tr-ai",
            "MIT TR · Artificial Intelligence",
            "tech",
            "https://www.technologyreview.com/topic/artificial-intelligence/feed",
        ),
        feed(
            "the-verge",
            "The Verge",
            "tech",
            "https://www.theverge.com/rss/index.xml",
        ),
        feed(
            "arstechnica",
            "Ars Technica",
            "tech",
            "https://feeds.arstechnica.com/arstechnica/index",
        ),
        feed(
            "conversation-ai",
            "The Conversation · AI",
            "tech",
            "https://theconversation.com/us/topics/artificial-intelligence-ai-90/articles.atom",
        ),
        feed(
            "platformer",
            "Platformer",
            "tech",
            "https://www.platformer.news/feed",
        ),
        feed(
            "last-week-in-ai",
            "Last Week in AI",
            "tech",
            "https://lastweekin.ai/feed",
        ),
        feed(
            "one-useful-thing",
            "One Useful Thing",
            "tech",
            "https://www.oneusefulthing.org/feed",
        ),
        feed(
            "benedict-evans",
            "Benedict Evans",
            "tech",
            "https://www.ben-evans.com/benedictevans?format=rss",
        ),
        feed(
            "stratechery",
            "Stratechery",
            "tech",
            "https://stratechery.com/feed/",
        ),
        feed(
            "daring-fireball",
            "Daring Fireball",
            "tech",
            "https://daringfireball.net/feeds/main",
        ),
        feed(
            "four-oh-four-media",
            "404 Media",
            "tech",
            "https://www.404media.co/feed/",
        ),
        feed(
            "guardian-tech",
            "The Guardian · Technology",
            "tech",
            "https://www.theguardian.com/technology/rss",
        ),
        feed(
            "simon-willison",
            "Simon Willison",
            "tech",
            "https://simonwillison.net/atom/entries/",
        ),
        feed(
            "understanding-ai",
            "Understanding AI",
            "tech",
            "https://www.understandingai.org/feed",
        ),
        feed(
            "karpathy",
            "Andrej Karpathy",
            "tech",
            "https://karpathy.github.io/feed.xml",
        ),
        feed(
            "lilian-weng",
            "Lilian Weng · Lil'Log",
            "tech",
            "https://lilianweng.github.io/index.xml",
        ),
        feed(
            "jay-alammar",
            "Jay Alammar",
            "tech",
            "https://jalammar.github.io/feed.xml",
        ),
        feed(
            "colah",
            "colah's blog",
            "tech",
            "https://colah.github.io/rss.xml",
        ),
        feed(
            "sam-altman",
            "Sam Altman",
            "tech",
            "https://blog.samaltman.com/posts.atom",
        ),
        feed(
            "latent-space",
            "Latent Space",
            "tech",
            "https://www.latent.space/feed",
        ),
        feed(
            "chinatalk",
            "ChinaTalk",
            "tech",
            "https://www.chinatalk.media/feed",
        ),
        feed(
            "the-diff",
            "The Diff",
            "tech",
            "https://www.thediff.co/feed",
        ),
        feed(
            "pragmatic-engineer",
            "The Pragmatic Engineer",
            "tech",
            "https://newsletter.pragmaticengineer.com/feed",
        ),
        feed(
            "balaji",
            "Balaji",
            "tech",
            "https://balajis.com/feed",
        ),
        // finance — business explainers, investing blogs, newsletters
        feed(
            "conversation-business",
            "The Conversation · Business",
            "finance",
            "https://theconversation.com/us/business/articles.atom",
        ),
        feed(
            "lennys-newsletter",
            "Lenny's Newsletter",
            "finance",
            "https://www.lennysnewsletter.com/feed",
        ),
        feed(
            "not-boring",
            "Not Boring",
            "finance",
            "https://www.notboring.co/feed",
        ),
        feed(
            "commoncog",
            "Commoncog",
            "finance",
            "https://commoncog.com/blog/rss/",
        ),
        feed(
            "noahpinion",
            "Noahpinion",
            "finance",
            "https://www.noahpinion.blog/feed",
        ),
        feed(
            "damodaran",
            "Aswath Damodaran · Musings on Markets",
            "finance",
            "https://aswathdamodaran.blogspot.com/feeds/posts/default",
        ),
        feed(
            "of-dollars-and-data",
            "Of Dollars And Data",
            "finance",
            "https://ofdollarsanddata.com/feed/",
        ),
        feed(
            "a-wealth-of-common-sense",
            "A Wealth of Common Sense",
            "finance",
            "https://awealthofcommonsense.com/feed/",
        ),
        feed(
            "collaborative-fund",
            "Collaborative Fund",
            "finance",
            "https://collabfund.com/feed",
        ),
        feed(
            "calculated-risk",
            "Calculated Risk",
            "finance",
            "https://www.calculatedriskblog.com/feeds/posts/default",
        ),
        feed(
            "avc",
            "AVC · Fred Wilson",
            "finance",
            "https://avc.com/feed/",
        ),
        feed(
            "big-picture",
            "The Big Picture",
            "finance",
            "https://ritholtz.com/feed/",
        ),
        feed(
            "marginal-revolution",
            "Marginal Revolution",
            "finance",
            "https://marginalrevolution.com/feed",
        ),
        feed(
            "abnormal-returns",
            "Abnormal Returns",
            "finance",
            "https://www.abnormalreturns.com/feed/",
        ),
        // world — classic free / open newsrooms (RSS + page fetch for full text)
        feed(
            "guardian-world",
            "The Guardian · World",
            "world",
            "https://www.theguardian.com/world/rss",
        ),
        feed(
            "guardian-international",
            "The Guardian · International",
            "world",
            "https://www.theguardian.com/international/rss",
        ),
        feed(
            "bbc-world",
            "BBC News · World",
            "world",
            "https://feeds.bbci.co.uk/news/world/rss.xml",
        ),
        feed(
            "aljazeera",
            "Al Jazeera English",
            "world",
            "https://www.aljazeera.com/xml/rss/all.xml",
        ),
        feed(
            "dw-english",
            "Deutsche Welle",
            "world",
            "https://rss.dw.com/rdf/rss-en-all",
        ),
        feed(
            "npr-news",
            "NPR News",
            "world",
            "https://feeds.npr.org/1001/rss.xml",
        ),
        feed(
            "france24",
            "France 24 English",
            "world",
            "https://www.france24.com/en/rss",
        ),
        feed(
            "globe-world",
            "The Globe and Mail · World",
            "world",
            "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/world/",
        ),
        feed(
            "globe-canada",
            "The Globe and Mail · Canada",
            "world",
            "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/canada/",
        ),
        feed(
            "globe-opinion",
            "The Globe and Mail · Opinion",
            "world",
            "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/opinion/",
        ),
        feed(
            "un-news",
            "UN News",
            "world",
            "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
        ),
        feed(
            "vox",
            "Vox",
            "world",
            "https://www.vox.com/rss/index.xml",
        ),
        feed(
            "the-atlantic",
            "The Atlantic",
            "world",
            "https://www.theatlantic.com/feed/all/",
        ),
        feed(
            "the-intercept",
            "The Intercept",
            "world",
            "https://theintercept.com/feed/?rss",
        ),
        feed(
            "democracy-now",
            "Democracy Now!",
            "world",
            "https://www.democracynow.org/democracynow.rss",
        ),
        feed(
            "scmp",
            "South China Morning Post",
            "world",
            "https://www.scmp.com/rss/91/feed",
        ),
        feed(
            "conversation-us",
            "The Conversation US",
            "world",
            "https://theconversation.com/us/articles.atom",
        ),
        feed(
            "conversation-world",
            "The Conversation · World",
            "world",
            "https://theconversation.com/us/world/articles.atom",
        ),
        feed(
            "propublica",
            "ProPublica",
            "world",
            "https://www.propublica.org/feeds/propublica/main",
        ),
        feed(
            "who-news",
            "WHO News",
            "world",
            "https://www.who.int/rss-feeds/news-english.xml",
        ),
        feed(
            "slow-boring",
            "Slow Boring",
            "world",
            "https://www.slowboring.com/feed",
        ),
        // politics / general news (page fetch fills short RSS)
        feed(
            "politico",
            "Politico",
            "world",
            "https://rss.politico.com/politics-news.xml",
        ),
        feed(
            "the-hill",
            "The Hill",
            "world",
            "https://thehill.com/news/feed/",
        ),
        feed(
            "npr-politics",
            "NPR Politics",
            "world",
            "https://feeds.npr.org/1014/rss.xml",
        ),
        feed(
            "bbc-politics",
            "BBC News · Politics",
            "world",
            "https://feeds.bbci.co.uk/news/politics/rss.xml",
        ),
        feed(
            "guardian-politics",
            "The Guardian · Politics",
            "world",
            "https://www.theguardian.com/politics/rss",
        ),
        feed(
            "conversation-politics",
            "The Conversation · Politics",
            "world",
            "https://theconversation.com/us/politics/articles.atom",
        ),
        feed(
            "pbs-newshour",
            "PBS NewsHour",
            "world",
            "https://www.pbs.org/newshour/feeds/rss/headlines",
        ),
        feed(
            "cnn-world",
            "CNN · World",
            "world",
            "http://rss.cnn.com/rss/edition_world.rss",
        ),
        feed(
            "time-magazine",
            "TIME",
            "world",
            "https://time.com/feed/",
        ),
        feed(
            "independent-world",
            "The Independent · World",
            "world",
            "https://www.independent.co.uk/news/world/rss",
        ),
        feed(
            "project-syndicate",
            "Project Syndicate",
            "world",
            "https://www.project-syndicate.org/rss",
        ),
        feed(
            "foreign-policy",
            "Foreign Policy",
            "world",
            "https://foreignpolicy.com/feed/",
        ),
        feed(
            "mother-jones",
            "Mother Jones",
            "world",
            "https://www.motherjones.com/feed/",
        ),
        feed(
            "reason",
            "Reason",
            "world",
            "https://reason.com/feed/",
        ),
        feed(
            "jacobin",
            "Jacobin",
            "world",
            "https://jacobin.com/feed/",
        ),
        feed(
            "national-review",
            "National Review",
            "world",
            "https://www.nationalreview.com/feed/",
        ),
        feed(
            "the-bulwark",
            "The Bulwark",
            "world",
            "https://www.thebulwark.com/feed/",
        ),
        feed(
            "persuasion",
            "Persuasion",
            "world",
            "https://www.persuasion.community/feed",
        ),
        feed(
            "the-dispatch",
            "The Dispatch",
            "world",
            "https://thedispatch.com/feed/",
        ),
        feed(
            "harpers",
            "Harper's Magazine",
            "world",
            "https://harpers.org/feed/",
        ),
        // other — classic blogs, science / space, longform
        feed(
            "nasa",
            "NASA Breaking News",
            "other",
            "https://www.nasa.gov/rss/dyn/breaking_news.rss",
        ),
        feed(
            "space-com",
            "Space.com",
            "other",
            "https://www.space.com/feeds/all",
        ),
        feed(
            "quanta",
            "Quanta Magazine",
            "other",
            "https://www.quantamagazine.org/feed/",
        ),
        feed(
            "live-science",
            "Live Science",
            "other",
            "https://www.livescience.com/feeds/all",
        ),
        feed(
            "conversation-science",
            "The Conversation · Science",
            "other",
            "https://theconversation.com/us/science/articles.atom",
        ),
        feed(
            "atlas-obscura",
            "Atlas Obscura",
            "other",
            "https://www.atlasobscura.com/feeds/latest",
        ),
        feed(
            "longreads",
            "Longreads",
            "other",
            "https://longreads.com/feed/",
        ),
        feed(
            "literary-hub",
            "Literary Hub",
            "other",
            "https://lithub.com/feed/",
        ),
        feed(
            "noema",
            "Noema Magazine",
            "other",
            "https://www.noemamag.com/feed/",
        ),
        feed(
            "paris-review",
            "The Paris Review",
            "other",
            "https://www.theparisreview.org/blog/feed/",
        ),
        feed(
            "wait-but-why",
            "Wait But Why",
            "other",
            "https://waitbutwhy.com/feed",
        ),
        feed(
            "the-marginalian",
            "The Marginalian",
            "other",
            "https://www.themarginalian.org/feed/",
        ),
        feed(
            "farnam-street",
            "Farnam Street",
            "other",
            "https://fs.blog/feed/",
        ),
        feed(
            "seth-godin",
            "Seth's Blog",
            "other",
            "https://seths.blog/feed/",
        ),
        feed(
            "james-clear",
            "James Clear",
            "other",
            "https://jamesclear.com/feed",
        ),
        feed(
            "cal-newport",
            "Cal Newport",
            "other",
            "https://www.calnewport.com/blog/feed/",
        ),
        feed(
            "mark-manson",
            "Mark Manson",
            "other",
            "https://markmanson.net/feed",
        ),
        feed(
            "ted-ideas",
            "TED Ideas",
            "other",
            "https://ideas.ted.com/feed/",
        ),
        feed(
            "open-culture",
            "Open Culture",
            "other",
            "https://www.openculture.com/feed",
        ),
        feed(
            "three-quarks-daily",
            "3 Quarks Daily",
            "other",
            "https://3quarksdaily.com/feed",
        ),
        // deep personal / essay blogs (full-text friendly)
        feed(
            "paul-graham",
            "Paul Graham Essays",
            "other",
            "https://raw.githubusercontent.com/Olshansk/pgessays-rss/main/feed.xml",
        ),
        feed(
            "idle-words",
            "Idle Words",
            "other",
            "https://idlewords.com/index.xml",
        ),
        feed(
            "derek-sivers",
            "Derek Sivers",
            "other",
            "https://sivers.org/en.atom",
        ),
        feed(
            "astral-codex-ten",
            "Astral Codex Ten",
            "other",
            "https://www.astralcodexten.com/feed",
        ),
        feed(
            "dynomight",
            "Dynomight",
            "other",
            "https://dynomight.net/feed.xml",
        ),
        feed(
            "melting-asphalt",
            "Melting Asphalt",
            "other",
            "https://meltingasphalt.com/feed/",
        ),
        feed(
            "kevin-kelly",
            "Kevin Kelly · The Technium",
            "other",
            "https://kk.org/thetechnium/feed/",
        ),
        feed(
            "craig-mod",
            "Craig Mod",
            "other",
            "https://craigmod.com/index.xml",
        ),
        feed(
            "austin-kleon",
            "Austin Kleon",
            "other",
            "https://austinkleon.com/feed/",
        ),
        feed(
            "naval",
            "Naval",
            "other",
            "https://nav.al/feed",
        ),
        feed(
            "neil-gaiman",
            "Neil Gaiman's Journal",
            "other",
            "https://journal.neilgaiman.com/feeds/posts/default",
        ),
        feed(
            "anil-dash",
            "Anil Dash",
            "other",
            "https://www.anildash.com/feed.xml",
        ),
    ]
}